import type { Metadata } from "next"
import { Varela } from "next/font/google"
import Script from "next/script"
import "@/shared/ui/globals.css"

const varelaSans = Varela({ weight: ["400"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${varelaSans.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        {children}
        <Script
          src={`https://api-maps.yandex.ru/v3/?apikey=${process.env.NEXT_PUBLIC_YANDEX_MAPS_API_KEY}&lang=ru_RU`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  )
}
